# ---------------- Service Account with ECR access (IRSA) --------------
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8cruddemoapp-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/EKS-ECR-Access-Role
spec:
  template:
    spec:
      containers:
        - image: 629981134890.dkr.ecr.ap-south-1.amazonaws.com/k8scruddemoapp:4a76a84
---
# ---------------- Spring Boot Deployment --------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8cruddemoapp-deployment
  labels:
    app: k8cruddemoapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8cruddemoapp
  template:
    metadata:
      labels:
        app: k8cruddemoapp
    spec:
      serviceAccountName: k8cruddemoapp-sa # <-- Added for IRSA
      containers:
        - name: k8cruddemoapp
          image: 629981134890.dkr.ecr.ap-south-1.amazonaws.com/k8scruddemoapp:4a76a84
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql:3306/students?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
---
# ---------------- Spring Boot Service ----------------
apiVersion: v1
kind: Service
metadata:
  name: k8cruddemoapp-service
  labels:
    app: k8cruddemoapp
spec:
  type: NodePort
  selector:
    app: k8cruddemoapp
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 32080  # optional
  template:
    spec:
      containers:
        - image: 629981134890.dkr.ecr.ap-south-1.amazonaws.com/k8scruddemoapp:4a76a84
